sudo: false
language: python

python:
  # - "2.6" #throws error on Travis' side?
  - "2.7"
  - "3.3" # throws error on Travis' side?
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"


before_install:
  - pip install -U dateparser lxml
  - pip install -U codecov

install:
  - pip install .

script:
  - pytest
  - coverage run tests/unit_tests.py

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.7-dev

cache:
  pip: true
