language: python

python:
  # - "2.6" #throws error on Travis' side?
  - "2.7"
  # - "3.3" #throws error on Travis' side?
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install -U dateparser lxml
  - pip install -U codecov

install:
  - pip install .

script:
  - pytest

after_success:
    - codecov

notifications:
  email:
    on_success: never
    on_failure: change
